//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Core.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyQuotes
    {
        public DailyQuotes()
        {
            this.VolumebyPrices = new HashSet<VolumebyPrices>();
        }
    
        public decimal DailyQuotesID { get; set; }
        public int StockID { get; set; }
        public System.DateTime DailyDate { get; set; }
        public float HighestPrice { get; set; }
        public float LowestPrice { get; set; }
        public float OpeningPrice { get; set; }
        public float PrevClosePrice { get; set; }
        public decimal AccTradeShares { get; set; }
        public float LatestTradePrice { get; set; }
        public int TradeVolume { get; set; }
        public float Change { get; set; }
        public float ChangeExtent { get; set; }
        public float AveragePrice { get; set; }
        public decimal TradeValue { get; set; }
        public int BuyVolume { get; set; }
        public int SellVolume { get; set; }
        public float BuyVolumeRatio { get; set; }
        public float SellVolumeRatio { get; set; }
        public int TradeCount { get; set; }
        public byte StockStatus { get; set; }
    
        public virtual ICollection<VolumebyPrices> VolumebyPrices { get; set; }
    }
}
