//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Core.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForeignDailyTradeDetails
    {
        public decimal TradeID { get; set; }
        public int StockID { get; set; }
        public System.DateTime TradeTime { get; set; }
        public decimal ForeignBuyShares { get; set; }
        public decimal ForeignSellShares { get; set; }
        public decimal SecuritiesBuyShares { get; set; }
        public decimal SecuritiesSellShares { get; set; }
        public decimal DealersBuyShares { get; set; }
        public decimal DealersSellShares { get; set; }
        public decimal DifferenceShares { get; set; }
    }
}
