//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Core.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeDetails
    {
        public TradeDetails()
        {
            this.UnOrders = new HashSet<UnOrders>();
        }
    
        public decimal TradeID { get; set; }
        public int StockID { get; set; }
        public float HighestPrice { get; set; }
        public float LowestPrice { get; set; }
        public System.DateTime TradeTime { get; set; }
        public byte StockStatus { get; set; }
        public byte TradeStatus { get; set; }
        public int AccTradeVolume { get; set; }
        public float LatestTradePrice { get; set; }
        public int TradeVolume { get; set; }
        public float BestBidPrice { get; set; }
        public int BestBidVolume { get; set; }
        public float BestAskPrice { get; set; }
        public int BestAskVolume { get; set; }
        public float Change { get; set; }
        public float ChangeExtent { get; set; }
    
        public virtual ICollection<UnOrders> UnOrders { get; set; }
    }
}
