//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.Core.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnOrders
    {
        public int BestTradeID { get; set; }
        public decimal TradeID { get; set; }
        public float BestBidPrice { get; set; }
        public int BestBidVolume { get; set; }
        public float BestAskPrice { get; set; }
        public int BestAskVolume { get; set; }
    
        public virtual TradeDetails TradeDetails { get; set; }
    }
}
